### ISSUE TITLE
Terrible performance on RX 550 And Intel i5 4590U. 

### ISSUE THREAD

**Issue by Arroi** [Engine-Simulator/engine-sim-community-edition#14]
I had downloaded the Engine Simulator with the intention of utilizing it for engine testing, designing and experimentation purposes. However, I encountered performance issues resulting in terrible latency and an absence of sound during gameplay.

Despite having followed the game from its inception, I was unable to experience smooth gameplay due to severe lagging and poor performance issues

Please let me know when this issue is addressed.

**Comment by Arroi** [comment]
The game's resource usage, including CPU, GPU, and RAM, appears to be moderate. However, despite this, the game experiences significant lagging issues.

Despite attempting all feasible solutions, I was unable to find a resolution to the issue at hand.

**Comment by ange-yaghi** [comment]
Hello, firstly have you followed the entire getting started tutorial? https://github.com/Engine-Simulator/engine-sim-community-edition/blob/master/tutorial/01_getting_started/01_getting_started.md

Secondly, the application's CPU usage is not moderate. It may seem that way because of how the operating system is reporting CPU usage, however, this reporting is misleading. The OS will usually average load out over your available cores even though not all applications are capable of utilizing more than one core at a time. Engine Simulator depends on single-core speed and the lagging issues you're mentioning are almost always caused by the simulation frequency being set too high, a CPU that is too slow, or both.

**Comment by Arroi** [comment]
I confirm that I followed the entire guideline for tutorial one.

Regarding your second answer, the CPU usage of the application is reported as above-average, high, or moderate. However, I acknowledge that this reporting may not be entirely accurate. I primarily use Windows 10 as my OS. In my experience, the game runs smoothly for smaller engines but does not perform well for medium to larger-sized engines.

Could you please provide more information on why this performance issue occurs? Additionally, I would like to know how to change the simulation frequency. While I confirm that I have followed the game from its start, I must admit that I forgot about it due to my busy life. Please let me know if there are any specific steps I can take to address this issue or if there is anything I have done incorrectly. I am committed to running the game to the best of my abilities."

**Comment by ange-yaghi** [comment]
Instructions for changing the simulation frequency are given in the tutorial which is why I asked if you read it. The tutorial also includes detailed instructions for how to interpret the gauges and determine the cause of runtime issues. Please check each of the dials as described in the tutorial and adjust the simulation frequency as also described in the tutorial.

If this still doesn't resolve the issue, then your CPU is unable to keep up with the demands of the audio processing. This is also discussed in the tutorial. I'm working on improvements to this area but for now, there isn't anything you can do to resolve this (except finding a more powerful computer or only using smaller engines that are less demanding).

**Comment by Arroi** [comment]
I appreciate your kind words and I am glad to have been able to provide helpful solutions.
